# Generated by Django 5.1.7 on 2025-03-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptions',
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'subscription')},
        ),
    ]
