# Generated by Django 5.1.7 on 2025-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_subscription_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
